Import("env")
Import("tag")
def make_objs(file_list, suffix, enviroment) :
    return [ enviroment.Object(file + '-' + suffix + '.o', file + '.cpp' ) for file in file_list ]

files = Split('callbacks entry graphics ship_data fuel_data terrain_data')
objs = make_objs(files, tag, env)
Return('objs')